### ISSUE TITLE
Filtering and parsing facilities

### ISSUE THREAD

**Issue by captain-yoshi** [biojppm/c4conf#1]
Is this library meant to do filtering like the YAML processor [yq](https://github.com/mikefarah/yq) does ? If it does, I guess I would have to implement the filtering logic (see example below) but that would not be too complicated because of the provided parsing facilities. Speaking of facilities, do you have a function that checks if a YAML node is a subset of another node ?

``` bash
# Filtering example using 'yq'
# Filters out every data sequences that does not match:
#     query.scene   == "box-1c" && 
#     query.request == "First Contact"
yq 'del(.data[] | select((.query.scene == "box-1c" and .query.request == "First Contact")|not))' < dataset.yaml
```
YAML file:
``` yaml
data:
- query:
    scene: box-1c
    request: First Contact
- query:
    scene: empty
    request: All Contact
- query:
    scene: empty
    request: First Contact
- query:
    scene: empty
    request: First Contact
```
After filtering:
``` yaml
data:
- query:
    scene: box-1c
    request: First Contact
```
